version: '3.4'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallengeapi
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
    ports:
      - "33000:80"
      - "33001:443"
